channels:
- conda-forge
dependencies:
- python=3.8.8
- pip
- pip:
  - mlflow
  - cloudpickle==1.6.0
  - lz4==3.1.10
  - psutil==5.8.0
  - scikit-learn==0.24.1
  - typing-extensions==4.0.1
name: mlflow-env
